# Generated by Django 3.0.8 on 2020-10-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(default=2, max_length=50, verbose_name='Yorum Başlık'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(max_length=15, verbose_name='Yorum Yapan'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(max_length=250, verbose_name='Yorum İçerik'),
        ),
    ]
