# Generated by Django 3.0.8 on 2020-11-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20201026_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_data']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_created']},
        ),
    ]
